export const reviews = [
  {
    img: "Ethan-C",
    alt: "Ethan C",
    name: "Ethan C",
    numReviews: 6,
    numStars: 5,
    text: "It has transformed how we manage our daily operations. The quality of the assistants is exceptional, and the personalized selection process always ensures the best fit for our team. We recommend it so much.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Demian-L",
    alt: "Demian L",
    name: "Demian L",
    numReviews: 3,
    numStars: 5,
    text: "The selection process at Iconic Assistant was seamless. We found a perfect match!",
  },
  {
    img: "Liam-A",
    alt: "Liam A",
    name: "Liam A",
    numReviews: 5,
    numStars: 4.5,
    text: "We're thrilled with our new assistant from Iconic Assistant. The support team is responsive and helpful.  Overall, we're very satisfied with the results.",
  },
  {
    img: "Mark-E",
    alt: "Mark E",
    name: "Mark E",
    numReviews: 2,
    numStars: 4.5,
    text: "The psychometric assessments at Iconic Assistant are top-notch, and we found a great match.",
  },
  {
    img: "Sharon-H",
    alt: "Sharon H",
    name: "Sharon H",
    numReviews: 5,
    numStars: 5,
    text: "Iconic Assistant has been a key partner in our business, helping us find an assistant who exceeds our expectations. The process, from consultation to onboarding, was smooth and professional. The assistant is proactive, detail-oriented, and now an indispensable part of our team.",
  },
  {
    img: "Sharon-H",
    alt: "Sharon H",
    name: "Sharon H",
    numReviews: 5,
    numStars: 5,
    text: "Iconic Assistant has been a key partner in our business, helping us find an assistant who exceeds our expectations. The process, from consultation to onboarding, was smooth and professional. The assistant is proactive, detail-oriented, and now an indispensable part of our team.",
  },
  {
    img: "Sharon-H",
    alt: "Sharon H",
    name: "Sharon H",
    numReviews: 5,
    numStars: 5,
    text: "Iconic Assistant has been a key partner in our business, helping us find an assistant who exceeds our expectations. The process, from consultation to onboarding, was smooth and professional. The assistant is proactive, detail-oriented, and now an indispensable part of our team.",
  },
  {
    img: "Liam-A",
    alt: "Liam A",
    name: "Liam A",
    numReviews: 5,
    numStars: 4.5,
    text: "We're thrilled with our new assistant from Iconic Assistant. The support team is responsive and helpful.  Overall, we're very satisfied with the results.",
  },
  {
    img: "Liam-A",
    alt: "Liam A",
    name: "Liam A",
    numReviews: 5,
    numStars: 4.5,
    text: "We're thrilled with our new assistant from Iconic Assistant. The support team is responsive and helpful.  Overall, we're very satisfied with the results.",
  },
  {
    img: "Liam-A",
    alt: "Liam A",
    name: "Liam A",
    numReviews: 5,
    numStars: 4.5,
    text: "We're thrilled with our new assistant from Iconic Assistant. The support team is responsive and helpful.  Overall, we're very satisfied with the results.",
  },
  {
    img: "Demian-L",
    alt: "Demian L",
    name: "Demian L",
    numReviews: 3,
    numStars: 5,
    text: "The selection process at Iconic Assistant was seamless. We found a perfect match!",
  },
  {
    img: "Demian-L",
    alt: "Demian L",
    name: "Demian L",
    numReviews: 3,
    numStars: 5,
    text: "The selection process at Iconic Assistant was seamless. We found a perfect match!",
  },
  {
    img: "Demian-L",
    alt: "Demian L",
    name: "Demian L",
    numReviews: 3,
    numStars: 5,
    text: "The selection process at Iconic Assistant was seamless. We found a perfect match!",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
]