export const reviews = [
  {
    img: "Ethan-C",
    alt: "Ethan C",
    name: "Ethan C",
    numReviews: 6,
    numStars: 5,
    text: "It has transformed how we manage our daily operations. The quality of the assistants is exceptional, and the personalized selection process always ensures the best fit for our team. We recommend it so much.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Demian-L",
    alt: "Demian L",
    name: "Demian L",
    numReviews: 3,
    numStars: 5,
    text: "The selection process at Iconic Assistant was seamless. We found a perfect match!",
  },
  {
    img: "Liam-A",
    alt: "Liam A",
    name: "Liam A",
    numReviews: 5,
    numStars: 4.5,
    text: "We're thrilled with our new assistant from Iconic Assistant. The support team is responsive and helpful.  Overall, we're very satisfied with the results.",
  },
  {
    img: "Mark-E",
    alt: "Mark E",
    name: "Mark E",
    numReviews: 2,
    numStars: 4.5,
    text: "The psychometric assessments at Iconic Assistant are top-notch, and we found a great match.",
  },
  {
    img: "Sharon-H",
    alt: "Sharon H",
    name: "Sharon H",
    numReviews: 5,
    numStars: 5,
    text: "Iconic Assistant has been a key partner in our business, helping us find an assistant who exceeds our expectations. The process, from consultation to onboarding, was smooth and professional. The assistant is proactive, detail-oriented, and now an indispensable part of our team.",
  },
  {
    img: "Andrea-F",
    alt: "Andrea-F",
    name: "Andrea F",
    numReviews: 1,
    numStars: 5,
    text: "Iconic provided a great candidate in less than a week. She was exactly what I needed. I've been working with my assistants for 3 months now and my partner is about to hire one for himself. Much more cost-effective than hiring local.",
  },
  {
    img: "Hernan-M",
    alt: "Hernan M",
    name: "Hernan M",
    numReviews: 1,
    numStars: 5,
    text: "Everything was excellent",
  },
  {
    img: "Sebi-R",
    alt: "Sebi R",
    name: "Sebi R",
    numReviews: 5,
    numStars: 5,
    text: "Excellent service!",
  },
  {
    img: "Lara-C",
    alt: "Lara C",
    name: "Lara C",
    numReviews: 1,
    numStars: 5,
    text: "Amazing experience. My virtual assistant is proactive and organized. Couldn't be happier!",
  },
  {
    img: "Ary-L",
    alt: "Ary L",
    name: "Ary L",
    numReviews: 2,
    numStars: 5,
    text: "Incredible service! My assistant handles everything efficiently and with care. Highly recommend!",
  },
  {
    img: "Robert-N",
    alt: "Robert N",
    name: "Robert N",
    numReviews: 3,
    numStars: 5,
    text: "Iconic Assistant provides highly qualified assistants perfectly aligned with our needs. Highly recommended!",
  },
  {
    img: "Lilian-B",
    alt: "Lilian B",
    name: "Lilian B",
    numReviews: 3,
    numStars: 5,
    text: "Super reliable. Iconic Assistants has made my life so much easier. Love their work!",
  },
  {
    img: "Juan-S",
    alt: "Juan S",
    name: "Juan S",
    numReviews: 3,
    numStars: 5,
    text: "Excellent service, looking forward to hiring another assistant!",
  },
  {
    img: "Hellen-C",
    alt: "Hellen C",
    name: "Hellen C",
    numReviews: 7,
    numStars: 5,
    text: "This level of service deserves every bit of the 5-star rating.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
  {
    img: "Brian-S",
    alt: "Brian S",
    name: "Brian S",
    numReviews: 7,
    numStars: 4.5,
    text: "The quality of the assistants at Iconic Assistant is impressive. The process was almost flawless, with only a minor delay in onboarding. Still, it's been a great experience overall.",
  },
]