name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main  # Deploy only when commits are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}
      
      - name: Update and Rebuild Frontend on DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@147.182.214.108 << 'EOF'
            cd /home/iconic_server
            git submodule update --remote --merge  # Pull latest submodule changes
            docker compose down --remove-orphans # Stop current containers
            docker compose up --build -d  # Start the containers again
          EOF
